### ISSUE TITLE
Problem in changing Width and height of screenshot 

### ISSUE THREAD

**Issue by keerthanank** [keerthanank/keerthanank#1]

**Comment by subanidha** [comment]
Use the javascript version of the TextureScale plugin

import System.IO;
 
 function TakeScreenShot (name : String) {
      yield WaitForEndOfFrame(); // this also captures gui, remove if you don't wanna capture gui
      var shot = new Texture2D(Screen.width,Screen.height,TextureFormat.RGB24,false);
      shot.ReadPixels(Rect(0,0,Screen.width,Screen.height), 0, 0, false); 
      if(shot.width > 1024 || shot.height > 768)
           TextureScale.Bilinear(shot,1024,(1024.0/parseFloat(Screen.width))*Screen.height);
      //shot.Apply(); //this is unecessary, if you don't wanna use the image afterwards
      var bytes = shot.EncodeToPNG();
      var file = new File.Open(Application.persistentDataPath + "/" + name + ".png", FileMode.Create);
      var binaryWriter = new BinaryWriter(file);
      binaryWriter.Write(bytes);
      file.Close();     
 }
